---
title: "SESraster-models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SESraster-models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Gotelli (2000) summarizes nine null model algorithms for species co-occurrence analysis based on how sums of species (originally rows) and sites (originally columns) are treated (i.e. fixed, equiprobable, or proportional sums; see Table \@ref(tab:table1)).
  
```{r table1, echo=FALSE}
library(kableExtra)
type <- c("Equiprobable", "Proportional", "Fixed")
typeabv <- c("equipr.", "prop.", "fixed")
typeinit <- c("E", "P", "F")
# Species - Sites
d <- data.frame("Rows" = c("Rows (Layer)"),
                type=type,
                paste0("SIM", c(1,7,2), ": ", typeinit, "-", typeinit[1], 
                        "<br>", paste("Species occur.", typeabv, "<br> Site rich.", typeabv[1])) ,
                paste0("SIM", c(6,8,4), ": ", typeinit, "-", typeinit[2], 
                        "<br>", paste("Species occur.", typeabv, "<br> Site rich.", typeabv[2])) ,
                paste0("SIM", c(3,5,9), ": ", typeinit, "-", typeinit[3], 
                        "<br>", paste("Species occur.", typeabv, "<br> Site rich.", typeabv[3])) )
colnames(d) <- c(" ", " ", paste0("", type))

kbl(d, dbooktabs = TRUE, align=c("r", "c", "c", "c"), escape = F, caption = "Nine null model algorithms for species co-occurrence analysis listed in Gotelli (2000).") %>%
  collapse_rows() %>%
  kable_styling(bootstrap_options = c("bordered")) %>%
  add_header_above(c(" " = 2, "Cols (Cell)" = 3), background = "#F2F2F2") %>%
  row_spec(0, background = "#F2F2F2") %>% # , extra_css = c("border-bottom-style: none", "", "", "")
  column_spec(1:2, bold = TRUE, background="#F2F2F2", border_right = TRUE) %>%
  column_spec(3:4, border_right = TRUE) %>%
  column_spec(3, background=c("#B4EEB4")) %>%
  column_spec(4, background=c("#FFFAFA")) %>%
  column_spec(5, background=c("#B4EEB4"))

```
  
  
Let's see how each of these algorithms behave with raster data. 
  

```{r setup}
library(SESraster)
```
